### ISSUE TITLE
v1.3 Google Authenticator export window controls

### ISSUE THREAD

**Issue by leftdisconnected** [Rookiestyle/KeePassOTP#100]
OS:  Windows 7 and Windows 10.2004
KeePass:  2.50
KeePassOTP:  1.3

Tools >> KeePassOTP -> Google Authenticator...
Though still usable, the window size seems to not match the control layout size such that the Cancel button extends beyond the non-resizable window.  Capture taken in Win7, but same behavior seen in Win10.

![KeePassOTP 1 3 GA export window controls A](https://user-images.githubusercontent.com/47964212/154860783-b47ba648-fdc1-41d0-80fe-597f83b3acfd.png)

**Comment by Rookiestyle** [comment]
I don't face this issue on my Windows 10 box, no Windows 7 available here

Anyways, please try the  attached version.
If you still experience this behaviour, please attach a [debug file](https://github.com/Rookiestyle/KeePassOTP/wiki/Create-a-debugfile#gui-plugin-options
[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/8110699/KeePassOTP.zip)
)

**Comment by leftdisconnected** [comment]
This issue appears resolved on both my Win7 and Win10 machines.  The columns are now narrower by default, but the prior width, which together extended beyond the window width, may have been a factor in causing this issue in the first place.  I cannot explain why this occurred for me on 2 different OS'es, yet could not be reproduced on your machine, but thanks so much for the fix and for all of your great plugins!

![KeePassOTP 1 3 GA export window controls B](https://user-images.githubusercontent.com/47964212/155002701-42116ebf-205d-40fa-b8c9-f89ee7201dd6.png)
