### ISSUE TITLE
One Line Update cmd for the readme?

### ISSUE THREAD

**Issue by uptoratlen** [Rookiestyle/KeePassOTP#101]
First: Awesome plug-in
Second: In the last days you are busy rolling out new versions.

After downloading the 3rd update in a few days, I came up with this one line to make it a bit more easy for myself.
Maybe you would like to add it in the readme? If not close the issue.

(works at least in Windows 11 and Ubuntu/Linux) 
`curl -fsSL github.com/Rookiestyle/KeePassOTP/releases/latest/download/KeePassOTP.plgx -O`

Of course I placed it in a script but that piece a spare here.
Cheers, 
and now I'm not afraid of any new updates in terms of downloading.....

**Comment by Rookiestyle** [comment]
Thanks for your feedback and glad to hear that you found a way that helps you in downloading new versions.

Any reason you don't use [EarlyUpdateCheck](https://github.com/Rookiestyle/EarlyUpdateCheck/) which is already mentioned in the readme?
It will notify you about updates and you can update all of my plugins (including already installed translations) plus some others in addition with the single click of a button - including KeePass restart to make use of the new versions

Aside from that: I will publish future releases in a different schedule

**Comment by uptoratlen** [comment]
No, beside it was not listed on the "KeePass Plug-in page". 
That explains why there is no "self Update Feature" :-)
Already installed. Thx. Have a nice day.
