### ISSUE TITLE
Add username to KeePassOTP > Google Authenticator dialog box

### ISSUE THREAD

**Issue by Richu75** [Rookiestyle/KeePassOTP#102]
I would like to request to add the username of an entry to be displayed in the OTP > GA dialog box.
I'm sure I'm not the only one with multiple entries for one service (ie gmail or o365), and when exporting these entries they are not distinguishable:

![keepassotp](https://user-images.githubusercontent.com/78730066/158333373-806f78b7-7e0d-4698-a72c-9f611d7e420f.jpg)

Thank you for considering and for a great plugin!

**Comment by Rookiestyle** [comment]
I misread your enhancement request.

Currently the plugin shows the entry'a group name and its title.
I'll add the entry's username as well and will publish a new release soon.

**Comment by Richu75** [comment]
Works like a charm, thank you
