### ISSUE TITLE
It doesn't work with Keypassium OTP

### ISSUE THREAD

**Issue by gkodinov** [Rookiestyle/KeePassOTP#105]
## Overview
I've set up OTP on [keepassium](https://keepassium.com/) on my iphone and I have installed the plugin. But I can't see the code being generated or the custom field being picked up.

## Steps to Reproduce
1. Set up Keepassium and keepass w/ plugin to open the same database from google drive
2. set up OTP for e.g. githib in keepassium via the QR code
3. observe that the plugin doesn't pick up the OTP data stored by keepassium

## Expected Behavior
Be able to generate OTP on Keepass

## Actual Behavior
I just see the custom field but not OTP generator

## Context
OS: Windows 11
KeePass Version: 2.51.1
Plugin Version: 1.4

**Comment by Rookiestyle** [comment]
I'm not able to use KeePassium, no iOS device.

Please attach an example database or describe more precisely how the custom field is named and whether it's content matches the otpauth format: https://github.com/google/google-authenticator/wiki/Key-Uri-Format
