### ISSUE TITLE
Issue with Displayed OTP Code

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [Rookiestyle/KeePassOTP#107]
## Overview
I’m running the latest version of Windows KeePass and this plugin.  I have the KTOTP column displayed in the database window.  I also have the KTOTP placeholder embedded in the auto type sequence of my entry.  I’m not able to log into a website using this code because it is incorrect at the time of login.  I compared the displayed code in KeePass to the another two-factor app on my phone as well as the exact same KeePass database synced to my phone.  I discovered the code displayed in the Windows KeePass UI lags about 20-25 seconds behind the code on my other two apps.  The order of the codes are in sync between Windows KeePass and the two databases on my phone but the timing is different.  

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1.  Open Windows KeePass
2. Find entry with TOTP code
3. Attempt login while code is still active during 30 second interval
4. Login fails
5. Compare code to database on my phone and see that it’s about 20-25 seconds behind

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
I expect the code in both places to have the same value and timing

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
The code displayed in Windows KeePass lags the code displayed on my phone by 20-25 seconds

## Context
[NOTE]: # (Provide any additional information you may have)
OS:  Windows 10 Enterprise 19042.1766
KeePass Version: 2.51.1
Plugin Version: 1.4

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Closing this issue because I figured out there’s a difference in the clock settings between the two devices and it appears my computer is lagged by ~22 seconds which would be the issue.  Unfortunately I can’t edit or sync the time because I’m not an admin…sigh.

**Comment by Rookiestyle** [comment]
In KeePassOTP settings for the entry, switch to the Use advanced options tab
In the Time correction section, select Use entry's URL (assuming, the URL is something like https://github.com/)
