### ISSUE TITLE
Importing mutliply OTP Seeds at once

### ISSUE THREAD

**Issue by MrScreemi** [Rookiestyle/KeePassOTP#108]
Hi

Google Auth can export multiple Sets of OTP in a single QR-Code. I managed to import a OTP to a already created entry in Keypass. But there are a lot of OTPs that i don't have entries in Keypass for.

Is it somehow possible to import multiple OTP Seeds and create new Databaseentries in Keypass for each OTP?

Thanks for the help!

**Comment by Rookiestyle** [comment]
This is a pretty complex topic.

You can export multiple OTP from Google Authenticator and use the QR code in KeePassOTP already today.
You need to do this starting from an existing entry.

If you want to import ALL, it would be neccessary to check for possibly matching entries based on OTP label and issuer or create new entries with just the OTP.

What do you expect the new entries to look like?

**Comment by MrScreemi** [comment]
Hi

Thanks for the reply. For me it would not be necessary to add them all to existing entries in the database.

Simply create a new category named "OTP import" or import them to the currently opened category. Those new entries could be simply named as the export data provides.  As far as I have seen the exported qr contains only two informations (Accountname and seed). 

Acountname
Otp

Example: 

Google.com (Test@gmail.com)
678123

Ty for your help.

**Comment by Rookiestyle** [comment]
I thought about that and do not plan to implement this.

Your usecase assumes that you have no entry in KeePass that already contain username and password and now OTP data shall be added.
Having only OTP data in KeePass would make it kind of Google Authenticator as windows program which is not it's intended use.

For the case where you already have matching entries, I'm.working onbsomething that will allow you to assign existing entries to the OTP data that you import

**Comment by MrScreemi** [comment]
I do have entries in KeePass but not for every otp I need. Some passwords are engraved in my memory or managed by an other password manager i have to use because my company says so. For those accounts I want to get rid of Google out when I am using my PC. Keypass could replace it then I would not have to use a different tool on my PC or have to get my mobile everytime I have to enter those otps.

Thanks for thinking about it! Sadly you did not see a usecase for it.
