### ISSUE TITLE
KeePassOTP hotkeys do not work on Russian sites

### ISSUE THREAD

**Issue by f1h0** [Rookiestyle/KeePassOTP#110]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

installed windows 10 and installed keepass
immediately installed the wonderful keepassOTP plugin
on my computer, the keyboard shortcuts are **shift+alt+2.**
when I previously had Windows 7, a window appeared where the 2FA pin code was automatically entered.
Now this window has disappeared on the new Windows 10, but this is not a problem. The problem is different, my 2fa pincodes are no longer entered on Russian sites
on all other sites is entered easily
github
docker
gmail
cloudflare

What am I doing asking for help?
I also checked the websites.
chrome and yandex browser, 2FA pincodes automatically by pressing hotkeys do not work on Russian sites
so far noticed on yandex.ru and mail.ru

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. installed the keepassOTP plugin from https://github.com/Rookiestyle/KeePassOTP
2. went to the site yandex.ru or mail.ru entered authorization data
3. I'm waiting for the 2fa pin code request window to appear
4. I press the hot keys shift + alt + 2 these keys are not occupied by the system or other programs
5. I expect that there will be an automatic entry of the pin code
6. nothing happens

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
so that the pin code is automatically entered by pressing the hot keys shift + alt + 2

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
actually on Russian sites yandex.ru and mail.ru
pin code is not entered

## Context
[NOTE]: # (Provide any additional information you may have)
OS:  windows 10 pro build 19044.1826
KeePass Version: 2.51
Plugin Version: 1.5.0

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
I can't reproduce this.
It sounds like KeePass is not able to match the website and the entry.

Does it work if you use a different hotkey?
Do the website title and the entry title match?
Does auto-type of username/password work for yandex?

If you can answer all 3 questions with *Yes*, please do the following
1. KeePass -> Options -> Advanced -> In the `Auto-Type` check `Always show global auto-type entry selection dialog`
2. Retry Auto-Type
3. What happens?

For Yandex I tried those two approaches. Both are working.

1. Create an entry with entry title Авторизация (This is the website title of https://passport.yandex.ru/)
4. Crewate an entry with entry title Yandex and an custom auto-type sequence like this: 
![image](https://user-images.githubusercontent.com/36454520/184549593-0d2da9bf-470a-4ca0-adeb-24949a9f2e0a.png)
Again, Авторизация is the website title that I tested.

**Comment by f1h0** [comment]
@Rookiestyle 
great, it worked.
also corrected URL conditions added signs *... *
I'm closing the issue as resolved
