### ISSUE TITLE
Incorrect OTP values being generated

### ISSUE THREAD

**Issue by johnwarh** [Rookiestyle/KeePassOTP#111]
I have keepass (ver2.5.2) and keepassOTP (ver1.5.0) loaded on two PCs (one with win11, the other with Win10).  

I have installed identical databases on both machines.  

When I compare  OTP values generated by both systems, the OTP values calculated on the win10 machine are incorrect, while on the Win11 machine they are correct.  I expected both machines to produce the same OTP values.

I was able to create a debug file for the Win10 installation, but could not do so for the Win11 installation.  I tried to upload the xml file, but your site will not accept it.  So, I changed the ext. to .txt

[Debug_KeePassOTP_20220923T040419Z.xml.txt](https://github.com/Rookiestyle/KeePassOTP/files/9630684/Debug_KeePassOTP_20220923T040419Z.xml.txt)

**Comment by Rookiestyle** [comment]
Sounds like a time difference between your two installations.
Please either correct the time on your Windows 10 installation or let KeePassOTP take care as described in #107 

If time is the same, let me know and I will reopen this.
