### ISSUE TITLE
hotkeys for entering OTP code 2FA instagram site does not work

### ISSUE THREAD

**Issue by rdbox** [Rookiestyle/KeePassOTP#113]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Added 2fa authorization to the application
2. Added a seed code to keepassOTP, everything worked successfully.
3. I press hot keys so that the code is automatically entered, there is no reaction to pressing the keys

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
after pressing the keys, a temporary code should be automatically added to the authorization input field

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)

## Context
[NOTE]: # (Provide any additional information you may have)
OS:  win 10
KeePass Version: 2.52
Plugin Version: 1.5.0.1

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)
at this stage I press there is no reaction

![image](https://user-images.githubusercontent.com/18515862/194693413-4b903f73-a5c8-4e6b-99ed-0325c57bcb07.png)

**Comment by Rookiestyle** [comment]
My plugin does not change the way global auto-type works.
Having said that:
* How did you set up global auto-type? (KeePass options "An entry matches...")
* What's the site's title as shown in your browser?

Do you by change use WebAutoType as well?
If yes, please use its "Create Entry from Web Page" hotkey and attach a screenshot of the created entry.

**Comment by rdbox** [comment]
![image](https://user-images.githubusercontent.com/18515862/194697792-8c7d01e8-8d62-4e5e-a428-ae00e6648ce5.png)
i have auto-type set to page url
https://www.instagram.com/accounts/login/

then I press hot keys to enter OTP
and I see how slippage occurs and is pressed
key {ENTER} as in my settings

I've seen this behavior on different sites.

**Comment by Rookiestyle** [comment]
> slippage?

How did you set up global auto-type? This refers to KeePass options in the AutoType action starting with "An entry matches..."
What's the site's title as shown in your browser?

**Comment by Rookiestyle** [comment]
I created a new test account and I'm able to logon withput any issues.
Only thing I observed: I have to place the cursor manually into the OTP field. If I don't do that, using Auto-Type does not have an effect

Global Auto-Type for username & password: Ctrl + Alt + A
Auto-Type for OTP: Alt + Shift + 2 as shown in your screenshot

**Comment by rdbox** [comment]
here is the video
 

https://user-images.githubusercontent.com/18515862/194720737-614e83be-4813-403d-898c-f1e96232d83c.mp4



![image](https://user-images.githubusercontent.com/18515862/194720731-1b9ebf4f-0ab3-4316-8c5d-c46d29d9e354.png)

**Comment by Rookiestyle** [comment]
I can't reproduce this.
It sounds like KeePass is not able to match the website and the entry.

Does it work if you use a different hotkey?
Do the website title and the entry title match?

Please do the following

KeePass -> Options -> Advanced -> In the Auto-Type section check *Always show global auto-type entry selection dialog*
Activate debug mode for KeePassOTP as described [here](https://github.com/Rookiestyle/KeePassOTP/wiki/Create-a-debugfile#gui-plugin-options) 
Retry Auto-Type

What happens?

Close KeePass and attach the debug file.

**Comment by rdbox** [comment]
@Rookiestyle 
yes you were right the problem is in incorrect URL search
i added this rule
https://www.instagram.com/?next=%2F
and everything worked
now I know how to correctly look for errors when the hotkey does not work automatically on the water when OTP.
you helped me find the instructions thank you.
Your plugin is the magic of automation and the genius of your ideas

**Comment by Rookiestyle** [comment]
Glad you solved it
