### ISSUE TITLE
Google rolls out passwordless Passkey support for Android and Chrome

### ISSUE THREAD

**Issue by rdbox** [Rookiestyle/KeePassOTP#114]
whether such a function implemented in the KeePass OTP application would be very interesting
https://android-developers.googleblog.com/2022/10/bringing-passkeys-to-android-and-chrome.html

**Comment by Rookiestyle** [comment]
KeePass is a password manager and KeePassOTP is a plugin for this password manager.

Based on your link "Passkeys are a significantly safer replacement for passwords".
If at all, support for that should be implemented in KeePass or a specific plugin for exactly that purpose.

I don't plan to use a plugin for a password manager to replace plasswords.
