### ISSUE TITLE
Nullpointer Exception?

### ISSUE THREAD

**Issue by Don-Pedro** [Rookiestyle/KeePassOTP#119]
With the latest version (1.6.1) I get a NULL-exception every time I try to create a new entry (by trying to open the context menu or open the menu "Entry"). A downgrade to V1.5 resolves the issue, the exception makes V1.6.1 almost unusable.

**Comment by Rookiestyle** [comment]
This was an issue with 1.6 and got fixed with 1.6.1

Please attach a screenshot of the error messafe

**Comment by Don-Pedro** [comment]
You're right, I tried with 1.6. The issue has been resolved with 1.6.1. I tried and it works, so I will close this issue.
