### ISSUE TITLE
Improve usage documentation, include step-by-step guide

### ISSUE THREAD

**Issue by ComFreek** [Rookiestyle/KeePassOTP#12]
## Summary

I had a hard time figuring out how to actually create a new TOTP entry in my database. The readme only discusses the options page that I could not even find:

![image](https://user-images.githubusercontent.com/1827709/89451011-d3956300-d75b-11ea-8c2c-e4cf99ad1a65.png)

## Added value

A step-by-step guide would ease using this plugin for newcomers.

## Example

1. Create a new entry with a title and username of your choice, but the password set as `{TOTP}`
2. Right-click that entry and select `Copy TOTP`. Confirm the then appearing request to first setup TOTP for that entry.
3. Paste your code...

**Comment by Rookiestyle** [comment]
I can update the readme to better explain how to add OTP to an entry.

I'm also interested in your issue of not seeing KeePassOTP's config screen and I need your support to analyze that.

1. Please replace your version of KeePassOTP.plgx with the one linked here: [Link to debug build](https://github.com/Rookiestyle/KeePassOTP/releases/tag/v0.13.0.1)
2. Try to access KeePassOTP's options and close KeePass.
3. A debug file will be created and I need it for further analysis. Please attach it to this issue

**Comment by ComFreek** [comment]
Thanks for your quick reply!

I tried your debug plugin and it actually showed KeePassOTP's options dialog to me! Nonetheless, I attached the debug file; it's renamed to .txt for uploading reasons. 

[Debug_KeePassOTP_20200811T082217Z.txt](https://github.com/Rookiestyle/KeePassOTP/files/5055706/Debug_KeePassOTP_20200811T082217Z.txt)

**Comment by Rookiestyle** [comment]
Thanks for your feedback, although this is a bit irritating for me.
As I did not change anything except adding a few more debug messages, I expected that the issue would remain.

Did you change anything and would you mind testing with version 0.13 (latest offical release) again?
You can activate debugmode by passing a parameter to KeePass during start: `KeePass.exe -debugplugin:keepassotp`

If the issue does not exist with version 0.13 either, I tend to close this and think about reworking the readme.

**Comment by snowbie** [comment]
> 
> 
> I can update the readme to better explain how to add OTP to an entry.
> 
> I'm also interested in your issue of not seeing KeePassOTP's config screen and I need your support to analyze that.
> 
>     1. Please replace your version of KeePassOTP.plgx with the one linked here: [Link to debug build](https://github.com/Rookiestyle/KeePassOTP/releases/tag/v0.13.0.1)
> 
>     2. Try to access KeePassOTP's options and close KeePass.
> 
>     3. A debug file will be created and I need it for further analysis. Please attach it to this issue

I am also having a hard time, but maybe it's because I misinterpreted the plugin. Is this only for _**new**_ OTPs? I already have several in Authy and when reading over the docs a few times, I was under the impression I'd be able to essentially transfer my authy seeds over to KeePass and generate from OTPs from there. Do I have to reset my OTPs one-by-one and import each individual QR to this plugin?

**Comment by Rookiestyle** [comment]
Closing this one.
@ComFreek Feel free to reopen if you face the issue again
