### ISSUE TITLE
OTP setup overwrites existing KeePassOTP.RecoveryCodes

### ISSUE THREAD

**Issue by Adambean** [Rookiestyle/KeePassOTP#120]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)
Scenario: You've decided to start using this plug-in because you like the idea of KeePass housing your OTPs in addition to your phone or whatever, however prior to using this plug-in you had MFA recovery codes as a string field in entries already like a good boy. You also noticed that this plug-in used field name "KeePassOTP.RecoveryCodes" so you used the entry search tool to replace whatever field name you were using for "KeePassOTP.RecoveryCodes" in bulk.

When you proceed to setup OTP on an entry your existing "KeePassOTP.RecoveryCodes" string fields will be overwritten.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Have a KeePass entry with a "KeePassOTP.RecoveryCodes" string field.
2. Proceed to Setup OTP and import your QR code.
3. The Recovery Codes field will not read the existing "KeePassOTP.RecoveryCodes" string field, it'll be empty.

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
When using Setup OTP any existing "KeePassOTP.RecoveryCodes" string field should be read into the Recovery Codes tab.

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
When you save your OTP your recovery codes would be lost.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10
KeePass Version: 2.52 (64-bit)
Plugin Version: 1.5

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
I will check this when I'm back home.
To be sure my understanding is correct:

KeePassOTP.RecoveryCodes should be preserved when setting up OTP for an entry and this is not the case as of now?
If OTP is already set up, KeePassOTP.RecoveryCodes is shown in the OTP details as expected and won't be cleared after changing something?

**Comment by Adambean** [comment]
Yep, that's correct on both points. No problem if OTP is already set up.

Having not checked the plug-in source code I suspect the Setup OTP form only checks for the existence of a "otp" string field to decide whether it should also retrieve the "KeePassOTP.RecoveryCodes" content, instead of looking for "KeePassOTP.RecoveryCodes" independently.
