### ISSUE TITLE
Import QR code from camera (WIA or similar)

### ISSUE THREAD

**Issue by Adambean** [Rookiestyle/KeePassOTP#121]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Provide a brief overview of what the new feature is all about)
During the Setup OTA it would be quite splendid if a QR code could be acquired via a camera. (Using [WIA](https://learn.microsoft.com/en-us/windows/win32/wia/-wia-startpage) or similar.)

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)
This would make the transfer of QR codes easier from mobile apps that permit transfer by displaying QR codes, such as Authenticaor Plus and Aegis.
Such mobile apps don't seem to let you export the QR code as a file, and even still that would be more of a faff to then transfer a file to the Windows PC and import it.

**Comment by Rookiestyle** [comment]
I'm not going to implement something like that, sorry.
Dealing with WIA will make the plugin not usable with *nix any longer.

It might be possible to connect your smartphone to your computer and do screen mirroring. You might need to disable screen protection so that the OTP app's screen can be mirrored.

**Comment by Adambean** [comment]
> Dealing with WIA will make the plugin not usable with *nix any longer.

That's a fair point. I forget KP is technically cross platform usually via Mono. (We use it via a NextCloud extension so I should have remembered!)

This likely wouldn't be possible without a cross platform C# image processor like [Emgu CV](https://www.emgu.com/wiki/index.php/Main_Page). (It's been a **very** long time since I've done any .NET development so I couldn't really scope out the size of such an integration.)
