### ISSUE TITLE
Please bring back the old GUI?

### ISSUE THREAD

**Issue by Darthagnon** [Rookiestyle/KeePassOTP#122]
## Summary
This is how KeePassOTP used to look, and it was perfect:
![KeePassOTP - setup simple](https://user-images.githubusercontent.com/20792748/212779941-ddd31dc3-e972-45c2-a387-7e2ff4c3e8a7.png)

This is how KeePassOTP looks now, and it's very busy with (unneeded?) extra fields and less compatibility with HiDPI screens:
![KeePass_ag0rPskDLP](https://user-images.githubusercontent.com/20792748/212780022-fae07314-5945-497b-b3aa-707761e2ed02.png)

Any chance you could bring back the old GUI? It was simpler and had all the information I needed... Current "Help" field takes up 2x the space of the previous version, and I've got no idea what "Issuer & User" is for (I have never used it). Help field could be reverted, Issuer & User could be moved to Advanced, and it would be perfect?

**Comment by Rookiestyle** [comment]
The old layout resulted in issues for other users depending on screen resolution and other topics. The "Help" section will not be reverted.
I can move the issuer section to advanced settings.

You mentioned "less compatibility with HiDPI screens"
Which issues do you face?

**Comment by Darthagnon** [comment]
> You mentioned "less compatibility with HiDPI screens"
> Which issues do you face?

Actually wondering if I misremembered. I thought there were some text issues in the main GUI, or I think it might have been in the plugin settings menu, where some text was cut off, but looking around, I can't find it anywhere so please disregard.

> I can move the issuer section to advanced settings.
I'd really appreciate that. Thank you.
