### ISSUE TITLE
Password + token in clipboard

### ISSUE THREAD

**Issue by amatacchieri** [Rookiestyle/KeePassOTP#125]
First of all thanks for the awful product, I'm using it extensively! 
I was wondering if there is any way to copy in the clipboard directly a combination of the password and oath in the format "password,oath", even from commandline or in any other way. Can anybody advise? @Rookiestyle 
Thanks!!

**Comment by Rookiestyle** [comment]
What would be the use case for that?

**Comment by amatacchieri** [comment]
it worked THANKS! I didn't realised I can get the same result with autotype, thanks a lot!
