### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by supportthemgroup** [Rookiestyle/KeePassOTP#126]
## Overview
I am receiving the following message when KeePass starts:

Error reading OTP sites. The underlying connection was closed. Could not establish trust relationship for the SSL/TLS secure channel.
https://2fa.directory/api/v3/tfa.json

## Steps to Reproduce
Start KeePass

## Expected Behavior
No error

## Actual Behavior
Above error message received.

## Context
KeePass Version: 2.53.1
Plugin Version: 1.6.3

I'll send a debug file when I can. I think the error only happens on the first start up each day.

Thank you.

**Comment by Rookiestyle** [comment]
Please try opening this link manually. I'm sure it won't work either.

KeePassOTP uses Windows / .NET to open this link and retrieve a list of websites that support two factor authentication.

**Comment by supportthemgroup** [comment]
Hi @Rookiestyle 

My Edge browser says:

NET::ERR_CERT_AUTHORITY_INVALID
Subject: 2fa.directory

Issuer: Cisco Umbrella Secondary SubCA lon-SG

Expires on: 17 Feb 2023

Current date: 14 Feb 2023

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIDRDCCAiygAwIBAgIEY+s+MjANBgkqhkiG9w0BAQsFADBAMQ4wDAYDVQQKDAVD
aXNjbzEuMCwGA1UEAwwlQ2lzY28gVW1icmVsbGEgU2Vjb25kYXJ5IFN1YkNBIGxv
bi1TRzAeFw0yMzAyMTIwODAwMzlaFw0yMzAyMTcwODAwMzlaMGoxCzAJBgNVBAYT
AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
MRYwFAYDVQQKDA1PcGVuRE5TLCBJbmMuMRYwFAYDVQQDDA0yZmEuZGlyZWN0b3J5
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApagWJQ9XNFbG5bfv/W+D
ku2G2SImAHCmRmAGHUI0c+p8XPFktF5+xaOCgcW74EJT1ki/kLnG9iL3cB5PHT+m
96snVYCJnPuQtZxieh8Wn8LYz+RV7pp5+FgyxQlYOJXPfCxLtFa4biBvynLjtpPG
6jVb4CGkVR+DG6iSrpQY4iBuDYaWv6xobKLDdlQTQWC6EmMXsAjPf2TY7PJp0tqD
W3Z9pJZ2QyTbgshmgquodVeoRMHE6fDiY6lFqZTmBaL+Xrcx0rgIwG+LKqZ3uMW4
g0g5kuUAFY8qqagrgNP8Gvhaz8APwSJEtR8mR5TZTgi0bemeEleqKYrNMuV6kAwG
ywIDAQABoxwwGjAYBgNVHREEETAPgg0yZmEuZGlyZWN0b3J5MA0GCSqGSIb3DQEB
CwUAA4IBAQB88Z3gmsKMIXb9DGxt2X1e6cMT251r09o46VZbkhSDuxKkXcuYyXNg
aMwUxZovYlf9m62OqccR7oWdMCZe3g3rkdwRE+mIcAiISn1Dd2mg/AQvgUZYNqwe
HVobmMYtySr0tSKDUs8KQyZVJb5pjg64fCODarbwIZbT3oKSJTPaI38VeyQNMQiC
EXBwo6XHsVja66JDIi/ZRnW7FQU5skWheL/fXc903ZXGyXOeF2SLS2jcgmSRdIJV
9KHo6mghLktjt3Stz2gpcVYtBbjU2cHWObp7+OnvCdR1sIFuIqhCp61D8sF+6ymP
GPZBB5A9HsFpTXP/Isa+W+iQVImAbYzt
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIENTCCAx2gAwIBAgIQVfbsv68wTgyD9QUf6XbbUTANBgkqhkiG9w0BAQsFADBx
MQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2Fu
IEZyYW5jaXNjbzEOMAwGA1UECgwFQ2lzY28xJTAjBgNVBAMMHENpc2NvIFVtYnJl
bGxhIFByaW1hcnkgU3ViQ0EwHhcNMjMwMjEyMjMwOTUyWhcNMjMwMjIzMjMwOTUy
WjBAMQ4wDAYDVQQKDAVDaXNjbzEuMCwGA1UEAwwlQ2lzY28gVW1icmVsbGEgU2Vj
b25kYXJ5IFN1YkNBIGxvbi1TRzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAKWoFiUPVzRWxuW37/1vg5LthtkiJgBwpkZgBh1CNHPqfFzxZLRefsWjgoHF
u+BCU9ZIv5C5xvYi93AeTx0/pverJ1WAiZz7kLWcYnofFp/C2M/kVe6aefhYMsUJ
WDiVz3wsS7RWuG4gb8py47aTxuo1W+AhpFUfgxuokq6UGOIgbg2Glr+saGyiw3ZU
E0FguhJjF7AIz39k2OzyadLag1t2faSWdkMk24LIZoKrqHVXqETBxOnw4mOpRamU
5gWi/l63MdK4CMBviyqmd7jFuINIOZLlABWPKqmoK4DT/Br4Ws/AD8EiRLUfJkeU
2U4ItG3pnhJXqimKzTLlepAMBssCAwEAAaOB+TCB9jASBgNVHRMBAf8ECDAGAQH/
AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQU6o7WXVNLLRvsMsRdm26hMR3F
Y9AwHwYDVR0jBBgwFoAURV/1m3EzJanATjwCRM886EYGFsQwTAYIKwYBBQUHAQEE
QDA+MDwGCCsGAQUFBzAChjBodHRwOi8vY3JsLnByb2QuY2FnZW5lcmF0b3IucGtp
LnN0cmxuLm5ldC9jYS5wZW0wQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybC5w
cm9kLmNhZ2VuZXJhdG9yLnBraS5zdHJsbi5uZXQvY3JsLnBlbTANBgkqhkiG9w0B
AQsFAAOCAQEAH7EyCTJT1CmoMXLodRR9hh0os9pJ3iGfhYlwGJPCsJaeysqEqk9d
RZnNTcQ03PtG0D6N0nyZqqUjGqG2OXQxGvgDxeNbVlr72jJDQ3lxZBNbDb1sBrCy
xrHVCRbUqHvZvqRNQRD8jrPFgh48VnwrlyiHEyo+TLjlrbwrOc+3Xyv4TvVmdulg
BBY3XBxE3NbouS+92oFfSr6Xqx66RFSfWf/Pgx5W1ETfvD6541iCbfupWUONzR67
RfwUsvWY06PLkfXYvTtUy3po6VT0LC/Hnfhbtb+uCRVFVbN5MpGQHsnEZBOQf1BP
nxaPsFvtGYxQEi4FowNcKyt+PZmRZqSMow==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEuzCCA6OgAwIBAgIJAcQ3zFeNvKYVMA0GCSqGSIb3DQEBCwUAMDExDjAMBgNV
BAoTBUNpc2NvMR8wHQYDVQQDExZDaXNjbyBVbWJyZWxsYSBSb290IENBMB4XDTE5
MDUyMTE5NTMxOFoXDTI0MDUyMTE5NTMxOFowcTELMAkGA1UEBhMCVVMxEzARBgNV
BAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDjAMBgNVBAoM
BUNpc2NvMSUwIwYDVQQDDBxDaXNjbyBVbWJyZWxsYSBQcmltYXJ5IFN1YkNBMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuFEhA5TkN8CiGmW7XjaUbuve
U274v0kt6hRW8UUakmbyLnkI4d/BBQrGW71LYiT2QH4UaoYuihTXjuyAlzDxJ9OQ
Vje2NB9RdE3FcUCISeW5GrQs7vF2xFrjs2TGgG4ZXjE/8WymgFZP50nsTJYf7VqL
1r6Brs59DAbbQ1rVvsz/DFxoE3ruFagSFcOF07/watUxFrAPV+S/kK6Nb5TqrI1j
32hK6i49ujavDcbbb12aozwdoyPSyhs4cB0sCXFHK/yEdaE4CNXEAH8EjKUuj6O2
QUvRtBGM480688BId0T0ws3q+hSzRiVJ+dYCr3iufmTrAMhVwc+EzGjlEfLyXwID
AQABo4IBlDCCAZAwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
UgYDVR0gBEswSTBHBgorBgEEAQkVAR0AMDkwNwYIKwYBBQUHAgEWK2h0dHA6Ly93
d3cuY2lzY28uY29tL3NlY3VyaXR5L3BraS9wb2xpY2llcy8wHQYDVR0OBBYEFEVf
9ZtxMyWpwE48AkTPPOhGBhbEMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly93d3cu
Y2lzY28uY29tL3NlY3VyaXR5L3BraS9jcmwvY2lzY291bWJyZWxsYXJvb3QuY3Js
MIGHBggrBgEFBQcBAQR7MHkwSQYIKwYBBQUHMAKGPWh0dHA6Ly93d3cuY2lzY28u
Y29tL3NlY3VyaXR5L3BraS9jZXJ0cy9jaXNjb3VtYnJlbGxhcm9vdC5jZXIwLAYI
KwYBBQUHMAGGIGh0dHA6Ly9wa2ljdnMuY2lzY28uY29tL3BraS9vY3NwMB8GA1Ud
IwQYMBaAFENzAN4kukAaQFQsfXzVAEiJDHCkMA0GCSqGSIb3DQEBCwUAA4IBAQC6
P7ugvpQSkNxrzY1ZM0Nd9Q3LaoTERS4ItcxMsswFPl7ID/3Vk3v3ZT6KgtCZ+Nh0
MUgZztLATHf42ZppdSkdMf1HfCmLSWORz/eK+fZxztE63M1EGiZJoe8qFKT9z6qx
iDD989jyjY74sYfiSo5nbhcb5meUrUO6MQvOO5pUnlhWsDiBUg+yBzyfVoLnGRlY
2t7UZVTUz5kbBNFieTIt86yaYAumgOqriz/dCgQltFySbOkrgg/PN7cRv3IWm84C
uKQ9prsXbXLLbl8U+bGRH119prl3zJyRnQ0D+ursCqUnIfziBdKv7yLsupGDGt+Q
oqLzmkMPYE+WZmEi+3j5
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDJjCCAg6gAwIBAgIIUW6l3kYeVMEwDQYJKoZIhvcNAQELBQAwMTEOMAwGA1UE
ChMFQ2lzY28xHzAdBgNVBAMTFkNpc2NvIFVtYnJlbGxhIFJvb3QgQ0EwHhcNMTYw
NjI4MTUzNzUzWhcNMzYwNjI4MTUzNzUzWjAxMQ4wDAYDVQQKEwVDaXNjbzEfMB0G
A1UEAxMWQ2lzY28gVW1icmVsbGEgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAO7ZjfBSCaz5EMYSiWYoXjHPP/w7xFT4bXa82lOZ9CJJXDQw
bZpBdmuqX9UWo769LIAaSUvkYEeZqcTsjrx/7juPKoOErhJY0cPK12LU9PbHXqEd
XESIqBjdOC5oiIFHhTAKuuKRlL7rhPYkYhZtgdll4h0FLIG+xNsMVfzJb7z69X8Y
vF9r1drLkd7oR2xHuRkXgzeblFVpF+DRF7WXNhLy0By38ZxtClxYUSitdz53W0ic
maelG7EyCVNVxARxn5waaphRvki1hkuqqrm3JdlV165zAOdSz3JKzRISQinCTQuT
+RK/w0qLsDTyOVO/mEIVWLXu/Z1NtuXgj/jhegcCAwEAAaNCMEAwDgYDVR0PAQH/
BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFENzAN4kukAaQFQsfXzV
AEiJDHCkMA0GCSqGSIb3DQEBCwUAA4IBAQBIEoceSPZLmo5sLmgDfQA+Fq5BKztL
qg8aAvZdrbdMEKEBr1RDB0OAhuPcaaVxZi6Hjyql1N999Zmp8qIw/lLTt3VSTmEa
29uPgjdMGLl9KyfZjARiA/PPvPdHTwg7TMJOet+w7P5nWabLNW55+Wc/JzCSFE30
+0Kdz/jojxlA/8t0xYLCdS2UK7zC4kuAbojHLJDbIQO3HeEWwVmg4FO89AHVvC4R
Y+V0t7SaEradv6tPG9DHX7PLwjQ/Xs95NGDIJTeFwCRqYUlBu9iZjIvKba0e0tST
Vuyw2+P2HuWazjBPawGrbfyw+uO3KO4WnNGjMutJJ920o8B5M8gW1+Ye
-----END CERTIFICATE-----

2fa.directory uses encryption to protect your information. When Microsoft Edge tried to connect to 2fa.directory this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 2fa.directory, or a WiFi sign-in screen has interrupted the connection. Your information is still secure because Microsoft Edge stopped the connection before any data was exchanged.

You can't visit 2fa.directory at the moment because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by Rookiestyle** [comment]
This is an issue with your browser, maybe related to a plugin or something similar.

The issue doe snot occur on my laptop running WIndows 11 22H2, Edge Version 110.0.1587.41 (64-Bit)

**Comment by dweimer** [comment]
@supportthemgroup 
> 
> My Edge browser says:
> 
> NET::ERR_CERT_AUTHORITY_INVALID Subject: 2fa.directory
> 
> Issuer: Cisco Umbrella Secondary SubCA lon-SG
> 
> Expires on: 17 Feb 2023
> 
Formerly OpenDNS, and now Cisco Umbrella had classified the site as phishing. I submitted it to them today to get it categorized but until it gets some other votes it will likely stay blocked. [https://domain.opendns.com/2fa.directory](https://domain.opendns.com/2fa.directory). You can add it to the exceptions for your own network settings to fix it until then.
