### ISSUE TITLE
Built-in OTP feature in KeePass

### ISSUE THREAD

**Issue by szepeviktor** [Rookiestyle/KeePassOTP#128]
Hello! I've noticed that recent KeePass releases have OTP built in.
What is your reaction to that?

**Comment by Rookiestyle** [comment]
Not sure what you mean?

KeePass offers TOTP since version 2.47 and my plugin allows to migrate in both directions since v0.24

You may use whatever you like

**Comment by szepeviktor** [comment]
I see! Then I rarely update. I think it was 2.43 up to yesterday.
