### ISSUE TITLE
Translated localization files don't work

### ISSUE THREAD

**Issue by FanXiangTM** [Rookiestyle/KeePassOTP#129]
Followed instructions exactly, translated localization files still don't work

---------------------------------------------------------------------------------

I needed to put it under the path of \ plugins \ translations \. I made a mistake. I used to directly put the Language.xml file in Plugins\ , so couldn't work

<DebugInfo>
	<General>
		<Plugin>
			<PluginName>KeePassOTP</PluginName>
			<PluginVersion>1.6.4.0</PluginVersion>
		</Plugin>
		<DebugTime>
			<DebugStart>20230301T122048Z</DebugStart>
			<DebugEnd>20230301T122057Z</DebugEnd>
		</DebugTime>
		<LogLevel>All</LogLevel>
		<OS>Windows &gt;= Windows 10 - Microsoft Windows NT 6.2.9200.0</OS>
		<DotNet>4.8.9032 (533320)</DotNet>
		<KeePass>2.53.1.20815</KeePass>
		<LoadedPlugins>
			<Plugin>
				<PluginName>KeePassOTP.KeePassOTPExt</PluginName>
				<PluginVersion>1.6.4.0</PluginVersion>
			</Plugin>
		</LoadedPlugins>
	</General>
	<DebugMessages>
		<DebugEntry>
			<Message>Reading translation failed</Message>
			<Counter>1</Counter>
			<Severity>Error</Severity>
			<DateTimeUtc>20230301T122048Z</DateTimeUtc>
			<Parameters>
				<Param>Translation file: D:\MyTools\KeePass\Plugins\Translations\KeePassOTP.zh.language.xml</Param>
				<Param>File does not exist</Param>
			</Parameters>
			<StackFrames />
		</DebugEntry>
	</DebugMessages>
</DebugInfo>

**Comment by Rookiestyle** [comment]
Please create a debug file and attach it here.

You need to close KeePass and create the file during KeePass start because translations are read when KeePass starts.

Instructions: https://github.com/Rookiestyle/KeePassOTP/wiki/Create-a-debugfile#startup-parameter

You don't even need to open a database, starting KeePass and closing it is sufficient.

**Comment by FanXiangTM** [comment]
> 请创建一个调试文件并将其附加到此处。
> 
> 您需要关闭 KeePass 并在 KeePass 启动期间创建文件，因为在 KeePass 启动时会读取翻译。
> 
> 说明： [ https: //github.com/Rookiestyle/KeePassOTP/wiki/Create-a-debugfile#startup-parameter ](https://github.com/Rookiestyle/KeePassOTP/wiki/Create-a-debugfile#startup-parameter)
> 
> 您甚至不需要打开数据库，启动 KeePass 并关闭它就足够了。

I needed to put it under the path of \ plugins \ translations \. I made a mistake. I used to directly put the Language.xml file in Plugins\ , so couldn't work

**Comment by Rookiestyle** [comment]
I'm glad to read you figured out the reason and could solve it.
