### ISSUE TITLE
Submenu of the taskbar icon appears on other screen when there are two screens

### ISSUE THREAD

**Issue by Nepumuk2000** [Rookiestyle/KeePassOTP#132]
## Overview
I use two screens most of the time. When I do so and right click on the taskbar icon to open the KeePass options menu, it opens on the same screen as the taskbar icon. However, if I select "KPOTP Auto-Type..." there, the submenu for this opens up on the edge of the second screen. This is a bit inconvenient and not very practical for quick navigation. Can this be changed? 

## Steps to Reproduce
1. Use 2 screens
2. Right click on taskbar icon of KeePass to open KeePass options
3. Select "KPOTP Auto-Type..."

## Expected Behavior
KPOTP submenu opens on same screen next to KeePass options menu.

## Actual Behavior
KPOTP submenu opens on other screen.

## Context
OS: Windows 11 Pro
KeePass Version: 2.53.1
Plugin Version: 1.6.4

**Comment by Rookiestyle** [comment]
Layout of context menus is controlled by Windows.

I can enforce opening it on the left side of the "main" tray menu but this will then be the case everytime which contradicts with Windows default behaviour.

Let me check whether I can somehow calculate the space required for that. If that's possible and I can get the available space on the same monitor, I can have it open left / right depending on that.
To set expecations: I'ld not be too optimistic, from Windows point of view there is one big screen that just happens to span two physical devices. You should observe the same with e. g. the explorer window as well?

**Comment by Rookiestyle** [comment]
I did not find a way to reliably override this Windows standard behaviour

**Comment by Nepumuk2000** [comment]
Thank you anyway for trying and for your work!
