### ISSUE TITLE
QR Code from Microsoft 365 account not supported

### ISSUE THREAD

**Issue by bschoelpen** [Rookiestyle/KeePassOTP#133]
## Overview

When trying to integrate my Microsoft 365 account by reading the QR code from screen, I failed. Unfortunately, Microsoft does not seem to provide to get the seed / settings in any way / format, which is currently compatible with KeePassOTP.

![image](https://user-images.githubusercontent.com/87546449/224998712-ce674245-6e93-4be3-86e8-2a6d4700d4a4.png)

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Read above example QR code (or any other QR code from a microsoft account) from screen:

![image](https://user-images.githubusercontent.com/87546449/224999069-7bf651f3-b10f-45e3-818f-64a25a54aca4.png)

2. The QR code is not going to be accepted. Neither the code shown in the example above, nor the URL is usable as seed.

## Expected Behavior

The QR code should be accepted.

## Actual Behavior
The QR code is not accepted.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10
KeePass Version: 2.51.1 (64-bit)
Plugin Version: 1.6.3

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
This QR can only be processed by Microsoft Authenticator.
It's not otp but somethinge called phonefactor.


This screen is shown to me when I want to set up two factor authentication.
Please *set up a different Authenticator app* and scan the QR code that is shown afterwards.
![image](https://user-images.githubusercontent.com/36454520/225409251-d67e5023-28a0-436e-a0ab-cf80f96ad790.png)

**Comment by deejayy** [comment]
Unfortunately, MS now offers the option to turn off ANY OTHER 2fa solutions other than MS Authenticator.
