### ISSUE TITLE
DNS-Lookups for each URL-Entity

### ISSUE THREAD

**Issue by RichardBeisser** [Rookiestyle/KeePassOTP#134]
Hello,

i am using Keepass 2.53.1 on RaspianOS Bullseye with Mono. 
I am also using KeePassOTP V 1.6.4

Although I have disabled option "Indicate if 2FA usage is possible", after starting KP, there is a DNS-Lookup for each URL in field URL of each entity.
These hundreds of DNS-Lookups slow down KP, especially when using mono on slow machines.

When I remove KeePassOTP for plugin-folder, KP stops making DNS-Lookups.

Solution:
Disable DNS-Lookups when option "Indicate if 2FA usage is possible" is disabled, or add another option to disable them.

Thanks.

**Comment by Rookiestyle** [comment]
This should be related to [TimeCorrection](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-fields#keepassotptimecorrection). Might be the current version of KeePassOTP calculates the time difference all the time, even if this field is not set to OWNURL.

Let me verify that and provide a fix in the next couple of days.
