### ISSUE TITLE
KeePassOTP not showing up in KeePass

### ISSUE THREAD

**Issue by JanSchrod** [Rookiestyle/KeePassOTP#139]
Hi,

i am new to GitHub, so please see after me.

I wanted to add your Plugin to make it easier to create OTP.
I added your Plugin by putting it in the plugin folder in keepass.

After that the plugin was detected in the plugin section in keepass itself.
I set a new master password for the seperate database. So it seems like it integrated without problems.
I was able to set a new password and if i now open Keepass there is a second log in for the seperate database.

If  i now want to open an old or new entry and try to set up the TOTP i am not seeing the plugin.
So for example i dont see anywhere where i can drag and drop a qr code to register for TOTP.

Unfortunately i am not seeing it anywhere to "connect" TOTP, so i cant seem to see it anywhere to register any 2fa.

Maybe i am just stupid and not seeing it anywhere but i think this could be an issue?

Thanks for your help.

Also these additional information:

OS: Windows 11 
KeePass Version: 2.54
Plugin Version: 1.6.6

[Debug_KeePassOTP_20230627T101657Z.txt](https://github.com/Rookiestyle/KeePassOTP/files/11881217/Debug_KeePassOTP_20230627T101657Z.txt

**Comment by Rookiestyle** [comment]
Welcome to GitHub :)

https://github.com/Rookiestyle/KeePassOTP#usage
> OTP settings are entry-specific. To setup, change, copy or auto-type the OTP, you may use the context menu of the respective entry.

Please open the entry's context menu (right mouse button) and you should see a KeePassOTP option.
Selecting the entry and using KeePass' "Entry" menu will work as well

**Comment by JanSchrod** [comment]
Right.

Just shows i am not the cleverest D:

Thanks for your help though.
Thought the context menu was inside the entry not just right click.
