### ISSUE TITLE
KeePassOTP hotkey disabled in OTP plug-in option

### ISSUE THREAD

**Issue by mathaefele** [Rookiestyle/KeePassOTP#147]
## Overview
Hi,

I'd like to set a key to auto-type the OTP number on a website using 2FA. But the field seems to be disabled in the options as the label appears in grey and the text input is not modifiable. 

![Screenshot at 2024-01-08 10-51-22](https://github.com/Rookiestyle/KeePassOTP/assets/20662668/6e409a5c-6c2b-4c2b-9a77-dab904acf6e4)

For now I could set OTP for one website but I have to put keepass in front, look for the right entry, right click on it, select KeePassOTP, copy OTP and paste it on my browser. It works, that's great, but it is a bit painful... A key shortcut would be so nice !

Maybe it is only a general keepass option missing, but I cannot find out which one. Thanks for your help.

## Steps to Reproduce
1. Standard installation of the OTP plug-in by copying the `KeePassOTP.plgx` file to the right directory

## Expected Behavior
Having a configurable Hot key for OTP

## Actual Behavior
Hot key for OTP not configurable

## Context
OS: ubuntu 22.04 with MATE
KeePass Version: 2.47
Plugin Version: 1.7
I am also using KeePassRPC 1.14.0.0 plug-in by the way

**Comment by Rookiestyle** [comment]
This is disabled on purpose when running in Linux.
Can you use the built-in hotkeys for Global Auto-Type and Global Auto-Type? See the *Integration* tab

When I run KeePass in my virtual Ubuntu, I can't define hotkeys for the KeePass built-in auto-types either and because of that, I implemented a similar check for my plugin's hotkey

**Comment by Rookiestyle** [comment]
You can try to enable the KPOTP column, doubleclicking the OTP shown therin will copy it to the clipboard.
Not a hotkey but maybe a bit less inconvinient.

**Comment by mathaefele** [comment]
Having the OTP in the columns displayed for each entry already helps, thanks. 

But for Global auto-type in the *integration tab* it is also disabled here and set to `external`. I guess it means it is defined somewhere in the system but I cannot find where. I can find the defined shortcuts (shut down, lock screen, launch terminal...) and change them if I want, but no clue how to set/change the key for the `Global auto-type` expected by KeePass. Any idea ?

**Comment by Rookiestyle** [comment]
I'm afraid I can't help.
I only found this: https://keepass.info/help/kb/autotype_wayland.html

My understanding of that:
It's not possible to check window names
It is only possible to auto-type the default sequence of the **selected** entry using a hotkey
It's not possible to auto-type anything else using a hotkey

**Comment by mathaefele** [comment]
Ok, fair enough. Thanks for having a close look at it.
