### ISSUE TITLE
2FA support no longer working due to the API being deprecated

### ISSUE THREAD

**Issue by zejjnt** [Rookiestyle/KeePassOTP#148]
## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Open KeePass 2
2. Add the "2FA Support" column via right clicking on another column, clicking "Comfigure Columns...", add 2FA Support if not already added.
3. Use eyes to tell and discover that said column is empty
4. Get disappointed and confused because it was there last time you checked. Decide to try and fix it.
5. Go to this Git in order to find info. Search the index page for "support". Find the URL which the function uses.
6. Go to that URL (https://api.2fa.directory/v2/tfa.json)
7. Recieve the JSON error message;
```
{
  "error": "This API version is no longer supported. Upgrade to version 3: https://2fa.directory/api/"
}
```
8. Create this bug report, try to be witty and not just a demanding entitled dimwit because you actually work in IT and deal with those all the time.
9. Ask nicely that someone has time to fix it, cross fingers.
10. Tell you that **the actual list is over** and the remaining points are moot.
11. Try to convey puppy eyes via text.
12. Remember that there is no way to do that.
13. Point out that you tried.
14. Still be somewhat sad.
16. ???
17. Profit.

## Expected Behavior
The "2FA Support" column should say "Yes" or "No".

## Actual Behavior
The "2FA Support" column is not populated.
![image](https://github.com/Rookiestyle/KeePassOTP/assets/20284369/42438f88-3c5d-4f94-a3ae-658a12a0788d)

## Context
OS: Windows 10 Enterprise x64
KeePass Version: 2.55 x86 installed
Plugin Version: Latest (v1.7)

**Comment by Rookiestyle** [comment]
17. Inform the creator of this issue that KeePassOTP does NOT provide a column named "2FA Support"
18. Ask the creator of this issue whether he uses the "KP2faChecker" plugin which provides this column?


KeePassOTP does not use https://api.2fa.directory/v2/tfa.json, it uses [https://api.2fa.directory/v3/tfa.json](https://api.2fa.directory/v3/tfa.json) instead which is working
In addition, column "KPOTP" will show "Setup 2FA" if 2FA is possible but not set up yet. If possible AND set up, it will show the OTP or - depending on your config - the "2FA defined" => No need for one more column "2FA Support"

**Comment by zejjnt** [comment]
Hi, thanks for the quick reply!

* Then why does both the plugin and the landing page of this git say that it does?
* I am not using KP2faChecker. It is very possible that I have done so in the past though.
* I did not look through the source code, the URL is listed on the landing page for this Git; https://github.com/rookiestyle/keepassotp/?tab=readme-ov-file#two-factor-authentication--internet-access

**Comment by zejjnt** [comment]
Hi, thanks for the quick reply!

* Then why does both the plugin and the landing page of this git say that it does?
* I am not using KP2faChecker. It is very possible that I have done so in the past though.
* I did not look through the source code, the URL is listed on the landing page for this Git; https://github.com/rookiestyle/keepassotp/?tab=readme-ov-file#two-factor-authentication--internet-access

EDIT: Installed KP2faChecker which made the column work again. Thank you for the hint.

**Comment by Rookiestyle** [comment]
> * Then why does both the plugin and the landing page of this git say that it does?
The plugin does not say so and the landing page says so because it's kind of documentation and... not 100% accurate.
Working in IT, this should not be a big surprise :)
