### ISSUE TITLE
Database won't open

### ISSUE THREAD

**Issue by molotovah** [Rookiestyle/KeePassOTP#149]
## Overview
Hi,

My database won't open but my OTP are still displayed in the "OTP Generator Settings".
Everytime I launch the app, it asks me the database password and then the OTP DB password (3 times and nothing happens).
Despite this, I can display my OTP codes and they are working.

Is there a way to display every entry that uses OTP in order to export the OTP shared secrets ? 

![image](https://github.com/Rookiestyle/KeePassOTP/assets/43416516/6680c3ef-710f-4c07-ac5d-48a455fdc521)

![image](https://github.com/Rookiestyle/KeePassOTP/assets/43416516/b6a776b7-8d08-426d-9838-8e66b892e347)

Thank you

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Open Keepass
2. Enter DB Password
3. It asks OTP DB password (3 times then nothing)
4. Go into settings to open DB
5. It asks OTP password
6. Nothing happens

## Context
OS: Windows 11 / Windows Server 2019
KeePass Version: 2.55
Plugin Version: 1.7

**Comment by Rookiestyle** [comment]
When the OTP doe snot open, you provide the wrong credentials.

You still see OTP codes because you do not use KeePassOTP for that. Your first screenshot shows the KeePass built in OTP functionality.
