### ISSUE TITLE
Hotkey systemwide instead of KeePass internal

### ISSUE THREAD

**Issue by UsefulVid** [Rookiestyle/KeePassOTP#15]
I opted for the hotkey
ctrl+t

I was used to it from an older plugin. It should only work if the keepass window is in focus.
Actually I am not able to press ctrl + t in my browser.
Looks like that this hotkey is registered system wide.
Is this intended?

**Comment by Rookiestyle** [comment]
This is the intended behaviour and mentioned in the readme
> configurable hotkey working inside and outside KeePass

If this conflicts with your browser, you can deactivate this hotkey or change it to different keys.

Although you can use the hotkey within Kee Pass itself, it's main purpose is to autotype the OTP.
For copying the OTP of the selected entry,  you can also use the context menu or doubleclick the KPOTP column.

**Comment by UsefulVid** [comment]
Ok sorry for not reading the readme.
If its for autotype you are right, this makes sense.
If I input my hotkey does KeepassOTP look up the "normal" autotype entry for matches and then only presents {totp} ?
Is it possible to change this to {totp}{enter}?
By the way: thanks for developing this addon.

**Comment by Rookiestyle** [comment]
KeePassOTP invokes KeePass' global autotype functionality and simply passes `{KPOTP}` (or whatever you defined) as placeholder.
If only one entry is found and you did not activate *Always show global auto-type entry selection dialog*, this OTP is auto-typed.

While this works, entries without valid OTP setup are shown as well. 
This can happen e. g. if the hotkey is pressed by accident.
If one of these entries is selected, actually nothing will happen but depending on your settings or the amount of found entries, the auto-type entry selection dialog is shown.

The next release will take care of that and only show entries with valid OTP setup, other entries found by KeePass will be removed from the result list silently.


I won't change this to `{KPOTP}{ENTER}` as this will be an unexpected change for other users.
As I'm currently working on the above, I'll add this as opt-in setting.
