### ISSUE TITLE
Add the value also to the TOTP column

### ISSUE THREAD

**Issue by nordxONE** [Rookiestyle/KeePassOTP#150]
## Summary
[NOTE]: # (Provide a brief overview of what the new feature is all about)
It would be nice if the original TOTP-column(s) would be adjusted too, so in other programs, the TOTP can be used too (for example on iOS in the app Strongbox you cant see the KPOTP, but you can see the original TOTP column)

a general setting in the plugin-configuration to make this happen would be good for people who want it or not.

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)
It would be usefull to manage my TOTPs with your plugin and at the same time have them nativ in every other app.

**Comment by Rookiestyle** [comment]
You can change the column name from *KPOTP* to any other value including *TOTP* in KeePassOTP's option.

If you do that, does it solve your issue?

**Comment by nordxONE** [comment]
Hey Rookiestyle,
thanks for your answer. I just didnt know how to convert it to a specific column-name (and also dont know if the original column is in fact called {TOTP} - since its a "Other Data"-Field (and i frankly dont know much about the structure of keepass so far), but i found the exact function i searched for in the OTP settings.

So i migrated everything from KeePassOTP -> KeePass and now it shows all my TOTPs in Strongbox 👍, awesome!

so every now and than i need to execute just this function and than it should work perfectly. THANKS!
