### ISSUE TITLE
Microsoft MFA Updated

### ISSUE THREAD

**Issue by Pandastarker** [Rookiestyle/KeePassOTP#151]
As maybe already noticed, Microsoft changed their MFA App Setup and added a different MFA confirmation, where a 2 digit code will be generated.
Is it possible to adapt this feature?
Would be helpfull for people, who dont want to install the microsoft authenticator or dont have a phone to do that.
Reason is because of security restrictions from companies, that don't accept different authenticators.

Since it is not a bug but a nasty new microsoft feature, i post it here.

**Comment by Rookiestyle** [comment]
I am aware of the following: https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-passwordless#microsoft-authenticator

According to that documentation, Microsoft sends this 2 digit number to the authenticator as push message and you as user need to compare the code shown in the app with the code shown on the website and you also need to authenticate in the app (fingerprint, ...)

KeePass cannot receive those push messages, it cannot be added.
