### ISSUE TITLE
Auto-type only types 1 digit.

### ISSUE THREAD

**Issue by WindFox** [Rookiestyle/KeePassOTP#152]
## Overview
Whenever I use auto-type for an OTP, it only types the first digit then stops. I have no issue with copy-paste, just auto-type.

## Expected Behavior
When using auto-type, it types all of the digits.

OS: Win 11
KeePass Version: 2.56
Plugin Version: 1.7.0

**Comment by Rookiestyle** [comment]
Which kind of auto-type? Shortcut, context menu?

Does it happen always or only for some sites?

**Comment by WindFox** [comment]
Both and always.

**Comment by Rookiestyle** [comment]
Please try the attached version.
It does not change the way Auto-Type is done but I added some debug info.

After you installed this version and restarted KeePass please do the following:
* Use Auto-Type in the context menu for one of your entries
* Use Auto-Type hotkey
* Auto-Type in the context menu for another entry
* Close KeePass

You will be asked to open a debug file.
Please attach this debug file here.

**Comment by WindFox** [comment]
[Debug_KeePassOTP_20240506T195132Z.zip](https://github.com/Rookiestyle/KeePassOTP/files/15225789/Debug_KeePassOTP_20240506T195132Z.zip)
I looked at it and it looks like it sees the whole thing, but it only types the first digit.
This is very odd.

**Comment by WindFox** [comment]
So, I may have found the issue. I just might be dumb.

I'll test it tomorrow on the app I need it to work with.

**Comment by WindFox** [comment]
Yup, I was just dumb.  I had the "Cancel auto-type when the target window title changes" option turned on. Little strange that it affected windows that didn't change the title but it's working now.

**Comment by Rookiestyle** [comment]
That is indeed very weird. If you like a more detailed check, you need to check with the KeePass author at https://sourceforge.net/projects/keepass/

My plugin only invokes KeePass' Auto-Type feature.
