### ISSUE TITLE
[Feature Request] KeePassOTP in a separate database

### ISSUE THREAD

**Issue by Redhousescheder** [Rookiestyle/KeePassOTP#154]
erstmal an dieser Stelle das Plugin ist Grandios. 
ich würde mich über die Option Freuen die OTP Datenbank außerhalb der Originaldatenbank zu Lagern also nicht Datenbank in Datenbank. 
Könnten sie diese Option Implementieren?

LG 
Enno

First of all, the plugin is fantastic. 
I would be happy about the option to store the OTP database outside the original database, i.e. not database in database. 
Could you implement this option?

LG 
Enno

**Comment by Rookiestyle** [comment]
That's not possible as there is no control of this separate database.

Why do you think you need it, maybe there is another solution for your use case?

**Comment by Redhousescheder** [comment]
> That's not possible as there is no control of this separate database.
> 
> Why do you think you need it, maybe there is another solution for your use case?

Wir möchten halt die MFA daten seperat von unseren Anderen Passwortdaten lageren. 

daher ist die Version Datenbank in einer Datenbank nicht so Smart. 
das Add on Bietet einen Extrem Guten Konfort beim einrichten neuer MFAs und diese würde wir ungeren Missen. 
daher die Anfrage ob es möglich ist die MFA DB außerhalb der Main DB zu Lageren. 
oder ob sie es möglich machen Könnten ?

We just want to store the MFA data separately from our other password data. 

Therefore the version database in a database is not so smart. 
the add on offers extremely good convenience when setting up new MFAs and we would not want to miss it. 
therefore the request if it is possible to store the MFA DB outside the Main DB. 
or if you could make it possible?

LG 
Enno

**Comment by Rookiestyle** [comment]
I tried various things but it is not possible to ensure data integrity for two databases that are logically linked to each other but completely separated physically.
Also I don't see any security benefit from that.


If you want to stoe the MFA data in a separate db you can do so. You can also use this plugin, simply go for storing the MFA data inside the entries itself - there are in a separate db anyhow.
You of course need to take efforts to have the entries itself duplicated...
