### ISSUE TITLE
Add an entry that displays the code

### ISSUE THREAD

**Issue by alexis26** [Rookiestyle/KeePassOTP#17]
hi,
I saw that you can display the code with 'KeePassOTP and OTP setup' by right-clicking on the entry (and that it turns red towards the end)...
But by doing this, the seed is pre-selected; if you only want to see the code (and not touch the setup) it's much too easy to make a mistake and modify the seed !...

I think it would be much better to add another entry to display a small window giving the code and the remaining time (without taking the risk to modify the config).
Thanks

**Comment by Rookiestyle** [comment]
This form is mainly intended to setup OTP.
You can copy the OTP by right-clicking or by double-clicking the KPOTP column. This column will also show the current OTP as well as the remaining time

<img src="https://github.com/Rookiestyle/KeePassOTP/blob/master/images/KeePassOTP%20-%20Column.png?raw=true" alt="KPOTP column" width="50%" height="50%"/>

What would be the benefit of having one more menu item?

**Comment by alexis26** [comment]
sorry, i havn't see and config the  KPOTOP column
(so maybe it will be ok, I'll have to see in real use...)

I was thinking about the possibility of displaying the code in a small window because more and more sites block the ctrl-v or right click in the 2FA field and also because a small moving window would allow to lose the keepass focus and give it to the site asking for the code (with the small window next to it) .

example with the old KeeOTP version
![Sans titre](https://user-images.githubusercontent.com/3404404/93671211-69cde000-faa1-11ea-8ded-e6e69e0c73bb.png)

(and really thank you for the keeOTP import option :-))

**Comment by Rookiestyle** [comment]
In addition, you can also define a hotkey to auto-type the OTP (like global auto-type) or use the entry's context tfor that purpose

**Comment by alexis26** [comment]
ty
