### ISSUE TITLE
phone app compatibility

### ISSUE THREAD

**Issue by alexis26** [Rookiestyle/KeePassOTP#18]
hello,
can we use bases containing OTP codes (generated with KeePassOTP) with keepass versions for phone, like KeePassDroid, keepass2android... ?
is it compatible?
thanks

**Comment by Rookiestyle** [comment]
KeePassOTP offers two ways of storing OTP data.

[OTP storage within the respective entry](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-storage-approaches#otp-storage-within-the-respective-entry) is compatible with e. g. KeePass2Android.
For other apps you need to try yourself. All apps that support the [otpauth format](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-fields#otp) should work
