### ISSUE TITLE
Steam OTP support?

### ISSUE THREAD

**Issue by molnarti** [Rookiestyle/KeePassOTP#19]
I am surprised this did not pop up among the issues yet, but having Steam OTP support would be great.  KeePassXC, Winauth and KeeTrayTOTP are supporting this, so grabbing some snippets for inspiration on how to implement it should be possible

**Comment by Figureix** [comment]
I too would love to see this--however, and to the best of my knowledge--Valve does not provide* users with a/the seed value for using other OTP programs outside of their application(s).

*I believe one can get this seed value from their rooted/jailbroken phone...

**Comment by molnarti** [comment]
there’s a lot of users who already have their steam otp seed in their keepass database, so it would be nice to be able to use it in the original keepass app as well, not just keepassxc. 
there are multiple ways how to get the steam otp seed, one of them described here https://www.reddit.com/r/Bitwarden/comments/a67c1n/steam_authenticator_supported_not_sure_how_to/

**Comment by Rookiestyle** [comment]
I'll have a look at this.

Adding Steam OTP support should not be an issue.
Confirming trades and other functionalities beside pure OTP generation will not be added as this is beyond this plugin's scope.

**Comment by koitsu** [comment]
Could this new feature please be documented in the KeepPassOTP Wiki?  Especially, relevant links to getting the Steam OTP seed and the likes.  I'm in the process of trying to figure out how to do this myself, but even the Reddit link previously mentioned returns "Sorry, we couldn't load posts for this page" and "Sorry, for some reason reddit can't be reached" right now.

I found [this resource](https://community.bitwarden.com/t/question-about-steam-totp-codes/3513/10) which describes part of the process -- and looks quite ridiculous.  Also, there is a comment there that reads:

> Thanks, was pulling the `shared_secret` field instead of from the `secret` parameter in the uri field URI. Your steps work.

This lead me to look for alternate information. I then [found this resource](https://keepassium.com/articles/how-to-setup-totp/#steam-totp-setup), which has a link labelled [How to get your Steam `shared_secret` key](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication).  Um, didn't the previous quote/user just say that `shared_secret` *is not* the correct field to pull from?

Also please note that getting the data off of an Android phone requires the phone be rooted, which basically is worthless for 99% of the population out there.  I know, I know, none of this is the fault of password database softwares, but the fact none of this stuff is well documented and has conflicting information does not lend itself well to the situation.  KeePass and its plugins should be above that.

**Comment by molnarti** [comment]
i got my steam OTP seed years ago, without ever trying out the steam mobile app. it may well happen that getting the OTP seed is not even possible anymore. the reddit link posted above works well for me. a few resources that may be worth looking into:
https://www.steamrobot.me/blog/HowtouseWinAuth
https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by Rookiestyle** [comment]
Thanks for your input.

A wiki page has been published based on koitsu's input.
