### ISSUE TITLE
Drag and drop of QR codes not working

### ISSUE THREAD

**Issue by Darthagnon** [Rookiestyle/KeePassOTP#28]
## Overview
I remember dragging and dropping QR code seeds onto the KeePassOTP window used to add the seed, but lately this hasn't been working with any site I've tried. I can't remember all the site names that have draggable QR codes that don't work, but I'll list the ones I do remember:

- https://windscribe.com

## Expected Behavior
Drag QR code from 2FA setup page onto the KeePassOTP window and it's added as a 2FA seed.

## Actual Behavior
Dragging the QR code onto the window does nothing. KeePassOTP window remains blank

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Win10 v1709
KeePass Version: 2.46 (latest as of writing)
Plugin Version: 0.18.2 (latest as of writing)

[NOTE]: Plugin is set to save my OTP stuff to the same database as the passwords, as entering my password twice for OTP access was a pain (and bypassed the point of my using Windows Hello plugin to unlock my database), and saving the OTP stuff to a database within the database feels really weird.

I couldn't get the GUI option to enable debug mode to work (box wouldn't stay ticked, didn't do anything); had to use command-line launch:
[Debug_KeePassOTP_20201101T120635Z.txt](https://github.com/Rookiestyle/KeePassOTP/files/5470776/Debug_KeePassOTP_20201101T120635Z.txt)

**Comment by Darthagnon** [comment]
Feature Request: Any chance you could add support for just pasting in the URL of the QR image in advanced settings, similar to [Winauth](https://github.com/winauth/winauth)?

I was able to import the seed for the OTP into KeePassOTP by adding the Windscribe OTP QR code URL to WinAuth, then exporting the data from WinAuth to a TXT file, which listed the otp URL with the seed (which I then pasted into KeePassOTP)

**Comment by Rookiestyle** [comment]
Actually, KeePassOTP tries to use the image's URL already today.
Appearently the currently used QR decoder is not able to decode the image / the image URL.

I will replace it by ZXing

**Comment by Rookiestyle** [comment]
[Version 0.19](../releases/tag/v0.19) now uses ZXing.net to read and write QR images.
I tested it successfully with Windscribe.

Pasting the `data:/image` URL used by Windscribe to display the QR image is possible as well.

Please re-open if not working for you.
