### ISSUE TITLE
Hide only OTP in Column "KPOTP" - Keep "Setup 2FA" visible and empty rows empty

### ISSUE THREAD

**Issue by An-dir** [Rookiestyle/KeePassOTP#33]
## Summary
Hide only the OTP Value in Column "KPOTP" - Keep "Setup 2FA" visible and empty rows empty
Still keep ability to copy/paste with doubleclick

## Added value
More security for the Column view due to:

- A simple overview where "Setup 2FA" is still possible, AND
- no one can visually see all your current otps in a table
- Additionally you still know where you do not have OTP enabled or documented

## Example
Currently it looks like this in my main window "entry view"
Title.................................Username..............................................Password......................KPOTP
Linkedin........................user@domain.com.............................xxxxxxxxxx.....................Setup 2FA
Cisco...............................user@domain.com............................xxxxxxxxxx.....................123 456 (5)
qnap...............................admin.....................................................xxxxxxxxxx.....................               
Router............................admin.....................................................xxxxxxxxxx.....................

What i can do with KeePass Options (No Setup 2FA) is not an option cause then i would have to document it manually in the title if there is a OTP configured/possible.
Title.................................Username..............................................Password......................KPOTP
Linkedin........................user@domain.com.............................xxxxxxxxxx.....................xxxxxxxxxx
Cisco...............................user@domain.com............................xxxxxxxxxx.....................xxxxxxxxxx
qnap...............................admin.....................................................xxxxxxxxxx.....................xxxxxxxxxx
Router............................admin.....................................................xxxxxxxxxx.....................xxxxxxxxxx

What i would like to have
Title.................................Username..............................................Password......................KPOTP
Linkedin........................user@domain.com.............................xxxxxxxxxx.....................Setup 2FA
Cisco...............................user@domain.com............................xxxxxxxxxx.....................yyyyyyyyyy
qnap...............................admin.....................................................xxxxxxxxxx.....................
Router............................admin.....................................................xxxxxxxxxx.....................

I wouldn't mind if "yyyyyyyyyy" would be "Copy OTP"

**Comment by Rookiestyle** [comment]
I plan to to this by offering a 2nd columm instead of adding even more configuration option

**KPOTP**
No change planned
If OTP is set up: Display current OTP
If OTP can be set up: Display *Setup 2FA*
If OTP is not possible: Column is empty

**KPOTP_Reduced**
New column
If OTP is set up: Display *2FA defined*
If OTP can be set up: Display *Setup 2FA*
If OTP is not possible: Column is empty
