### ISSUE TITLE
Too many versions

### ISSUE THREAD

**Issue by pbl987** [Rookiestyle/KeePassOTP#34]
## Summary
Version spamming. There are too many versions coming out!
Keepass urges the user to update the outdated plugin.
This has to be done manually.
Tedious.

## Added value
Collect minor improvements and convenience features into a bigger update.
Users that need it earlier could use a RC or something.

## Example
E.g. current change is: "You can now migrate these settings between KeePass and KeePassOTp in both directions"
How often do you do that? How many users need that now? 
They can do that manually if they need to.
(i dont want to imply that you shouldnt add new functions-thats great work!)

I suggest an update as often as other plugins do it, so they can be updated all at once.
I hope i dont sound rude or something, i really appreciate your plugin.
Thank you.

**Comment by Rookiestyle** [comment]
I'm not sure whether this plugin can be compared to other plugins that exist for a mcuh longer time and thus are most likely more feature-complete.
Release frequency will for sure decrease as more as more features are integrated.
Publishing release candidates is something I won't do. Users need to actively monitor the plugin homepage which is much more inconvenient and time consuming than simply ignoring the information about a new release

In addition, I have difficulties understanding your pain.
> Keepass urges the user to update the outdated plugin.

KeePass does not urge you, that's more you feeling urged.
KeePass informs you about newer versions once per day, **if** you activated the update check.
If you don't like KeePass informing you on a daily basis, why do you have the update check active? 
You can always check manually in whatever timeframe you prefer

> This has to be done manually.
> Tedious.

No, [EarlyUpdateCheck](https://github.com/Rookiestyle/EarlyUpdateCheck) can assist. 
You still have to confirm the update, the update itself as well as the required restart will be done automatically - all of that before you even needed to enter your masterkey to open your database

> I suggest an update as often as other plugins do it, so they can be updated all at once.

As mentioned above, release frequency will for sure decrease.
Nevertheless I don't plan to follow release schedules (does something like that even exist?) of whatever other plugin you might use.

> I hope i dont sound rude or something, i really appreciate your plugin

You did not, thanks for using KeePassOTP
