### ISSUE TITLE
Unable to add OTP for AWS SSO Credentials

### ISSUE THREAD

**Issue by ankitosh** [Rookiestyle/KeePassOTP#35]
Unable to add OTP for AWS SSO Credentials

**Comment by Rookiestyle** [comment]
I was able to setup virtual mfa as described here https://aws.amazon.com/de/iam/features/mfa/
To do so, I dragged the QR code image to the corresponding field in the OTP setup form of KeePassOTp.
In addition, I tested with manually copy/pasting the secrekt key and was successful as well.

What exactly is not working for you?

**Comment by ankitosh** [comment]
While registering for AWS SSO User MFA Device it gives error as
"An unexpected error has occurred
If the error persists, please contact your administrator."
For registering MFA of IAM User below error 
"
Invalid MFA Code
The multi-factor authentication (MFA) could not be verified. Either the code that you entered is not valid or you're not using a supported MFA device. Learn more
Authentication code for device is not valid."

This plugin is best for KeePass creds with OTP. I really love this to work.

**Comment by Rookiestyle** [comment]
You do use the virtual mfa as described here https://aws.amazon.com/de/iam/features/mfa/ ?

If you scan the QR code on the setup page with e. g. Google Authenticator, does it show the same OTP codes as KeePassOTP?

**Comment by ankitosh** [comment]
Yes, we are using AWS SSO user & MFA device.
This was working untill the version 0.2.10

**Comment by Rookiestyle** [comment]
Yoe refer to KeePassOTp 0.2.10? There was never such a version.
Version 0.2 was released April 1st 2020
Version 0.3 was released April 3rd 2020

Once again: If you scan the QR code on the setup page with e. g. Google Authenticator, does it show the same OTP codes as KeePassOTP?

**Comment by Rookiestyle** [comment]
If the issue still exists and you can provide additional required information, I'll reopen this.
For the time being, I close this issue due to inactivity
