### ISSUE TITLE
Error reading OTP sites: File does not exist

### ISSUE THREAD

**Issue by tty7tyil** [Rookiestyle/KeePassOTP#36]
## Overview
First time installing this plugin, this error popup upon the first launch.  (see picture below)
![Snipaste_2021-02-05_12-51-43](https://user-images.githubusercontent.com/13289283/106991734-cb24f000-67b1-11eb-8bfb-2c475c01b7ca.png)

## Steps to Reproduce
Seems like just some internet issue, not very clear how to reproduce.  **But**, what is this query for?  Is it a good idea to query the internet every time at KeePass launch by default?

## Context
OS: Windows 10 20H2
KeePass Version: 2.47
Plugin Version: 0.24

**Comment by tty7tyil** [comment]
To be clear: this ‘bug’ is very likely to do with my wonky network setup, the point is WHY do this internet query?

**Comment by tty7tyil** [comment]
Never mind, I see it can be disabled in the settings.

**Comment by Rookiestyle** [comment]
To answer the 'why':
KeePasaOTP will 
> indicate possible 2FA usage
<img src="https://raw.githubusercontent.com/Rookiestyle/KeePassOTP/master/images/KeePassOTP%20-%20options%202.png" alt="Options 2" height="50%" width="50%"/>
(readme)

Uncheck this option and the file will not be downloaded

I will update the readme to make this clearer.

**Comment by tty7tyil** [comment]
My apologize for being too impatient to check the settings and readme first 😂
