### ISSUE TITLE
otpauth construction used literal reference string

### ISSUE THREAD

**Issue by tty7tyil** [Rookiestyle/KeePassOTP#37]
## Overview
When the entry title or username is set to a reference string (for example, username: `{REF:U@I:326}`), the literal reference string is being used in the _label_ part of otpauth link (`otpauth://totp/title:{REF:U@I:326}?secret=testseed&issuer=title`).  
This will cause some compatibility problems in other clients.

## Steps to Reproduce
1. create an entry with its title or username set as a reference
2. setup totp for this entry
3. check the result `otp` field of this entry

## Expected Behavior
resolve the reference or avoid using it directly

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10 20H2
KeePass Version: 2.47
Plugin Version: 0.24

**Comment by tty7tyil** [comment]
See also: #38

**Comment by Rookiestyle** [comment]
Good catch. 
I'll work an resolving these references and will release a fix soon.
