### ISSUE TITLE
options to store otpauth with the bare minimum form

### ISSUE THREAD

**Issue by tty7tyil** [Rookiestyle/KeePassOTP#38]
## Summary
Add an option in the settings to use the bare minimum form of otpauth, aka with no _label_ and only mandatory parameters.

## Added value
Simplify the construction of otpauth link, minimize the possibility of generating invalid url, which will cause problem in some other clients.

## Example
`otpauth://totp/?secret=testseed`
instead of
`otpauth://totp/title:username?secret=testseed&issuer=something`

**Comment by Rookiestyle** [comment]
Issuer and label are not mandatory but every client should be able to either process them or - at least - to ignore them.

Which clients do have issues with a valid otpauth string containing isser and label?
best solution would be to have these clients corrected and enable them to properly use a valid otpauth string.

**Comment by tty7tyil** [comment]
You are right.  But it needs precise implementation to ignore label and issuer since these strings can be all over the place (nonascii, strange symbols, missed scenarios, etc).  Add an option to just not include them will increase the tolerance of other clients (mostly mobile platform clients …).

One example is that KeePassDX (an android client) will be confused by the colon in the reference string 😂

**Comment by Rookiestyle** [comment]
If you refer to the colon in {REF:U:I...} this will be fixed soon (today / tomorrow)
Placement of issuer and label fields is described and after #37 is fixed, there should be no malformed string anymore.
They canot occur all over the place.

Except the reference issue which results in a malformed otpauth string, it's up to each app to parse the otpauth string in a proper way.
I favour the idea of raising tickets for the respective app after I fixed the reference issue.

**Comment by tty7tyil** [comment]
If the handling of arbitrary string to url is not gonna be a problem (I mean in general, not the reference bug), then I have no other _practical_ reason to back this feature.

**Comment by Rookiestyle** [comment]
The reference bug is fixed in the new release, in case you face additional issues I'll reopen this issue
