### ISSUE TITLE
Translation problem with version v0.25

### ISSUE THREAD

**Issue by Havokdan** [Rookiestyle/KeePassOTP#43]
After I upgraded to version 0.25 of the plugin, the translation started to present the following problem:

![Sem título](https://user-images.githubusercontent.com/6549729/107119017-91142680-6863-11eb-8b08-3b4cc3231cad.png)

So the translation doesn't work, I emphasize that the problem started to occur before the pull requests I made today.

I'm on windows 10 x64, Keepass 2.47.

**Comment by Rookiestyle** [comment]
I manually edited the previous and now fixed the parsing error.
Please download the translation file again.

**Comment by Havokdan** [comment]
Via automatic update of your other plugin the update is not possible, I will try it manually.

**Comment by Rookiestyle** [comment]
> Via automatic update of your other plugin the update is not possible, I will try it manually.

Due to the Error in the translation file, the file cannot be parsed.
As it cannot be parsed, EarlyUpdateCheck can not handle it.

In future this won't happen again
