### ISSUE TITLE
Remove items from KPOTP auto-type list

### ISSUE THREAD

**Issue by robertl87** [Rookiestyle/KeePassOTP#44]
Hi,
In my KPOTP auto-type list (right click on the KeePass icon in tray) I see items for which I didn't configure 2FA. When I open the items in my database, nothing like 2FA/OTP/KPOTP settings can be found. Can I clean up this list?
I think the "Indicate if 2FA usage is possible" option found items in my database that have the possibility to have 2FA, but I don't use 2FA on those sites. I turned this option off, but that didn't help.
Thanks in advance for your reply.

**Comment by Rookiestyle** [comment]
The entries should have a string field named `otp` or `KeePassOTP.DB` defined. One of them is used based on the selected storage approach for the OTP secrets.

Do you mean that none of them is maintained in the entry?
Do you see all entries in the tray menu?

**Comment by robertl87** [comment]
The specific entries don't have any string value. This is an example of one of the entries listed:
![Entry](https://i.imgur.com/iytgx4h.png)

This is the list I see in my tray:
![Tray](https://i.imgur.com/JFEg0wc.png)
Only Jira and Confluence have an OTP string.

There are more entries without an OTP string in my DB and they are not visible.

**Comment by Rookiestyle** [comment]
Seems, the plugin does search for "otp" to be contained anywhere and it is e. g. part of *Sho**ot**proof*.
This will be fixed pretty soon.

I'm unsure regarding KeePassHttp and the *Version* entry.
If there is any field containing *otp* (part of the username, part of the url, ...) it would explain these entries' appearances as well.

**Comment by Rookiestyle** [comment]
Please test the prerelease: https://github.com/Rookiestyle/KeePassOTP/releases/tag/v0.25.1

**Comment by robertl87** [comment]
Yes, this version fixes the issue: with this version I only see the Jira and Confluence entry and not the other ones listed above. Thanks!
