### ISSUE TITLE
Is this basically an alternative for Google authenticator or Authy?

### ISSUE THREAD

**Issue by vespino** [Rookiestyle/KeePassOTP#47]
So forgive me for maybe asking a stupid question, but is this plugin an alternative for Google authenticator or Authy? If yes: how would I go about using this on my phone?

**Comment by Rookiestyle** [comment]
KeePassOTP is a plugin for KeePass and as such requires Kee pass to be installed on your computer.
It can 
* generate OTP codes
* import Google Authenticator sata
* display OTP data that can then be scanned by e.g. Google Authenticator or Authy

It is **not** an app for your smartphone and thus no replacement for those apps.

**Comment by vespino** [comment]
Still don’t understand the difference. Guess it could work as a replacement if I wouldn’t need it on a phone?

**Comment by Rookiestyle** [comment]
Yes

If you don't need it on a phone, you can use it as a replacement.

Basic requirement: It's a KeePass plugin and as such requires KeePass to be used as password manager. It's not a standalone program.

**Comment by vespino** [comment]
Clear, thanks.

**Comment by vespino** [comment]
Is it possible to sync data to multiple devices?

**Comment by Rookiestyle** [comment]
All data is stored in a KeePass database, this database can be synchronized.
I suggest to have a look at KeePass itself: https://keepass.info + SourceForge support forum for KeePass
