### ISSUE TITLE
2FA check doesn't work any longer

### ISSUE THREAD

**Issue by ankrman** [Rookiestyle/KeePassOTP#49]
## Overview
The domain twofactorauth.org was sold, so the 2FA check doesn't work any longer. See https://github.com/2factorauth/twofactorauth/issues/5238 for details. 

## Steps to Reproduce
1. Visit https://twofactorauth.org

## Expected Behavior
Result of check

## Actual Behavior
"Checking 2FA" all the time in KeePass

## Context
Would be great if you could support the new domain https://2fa.directory/ - or even better - support https://www.dongleauth.info/, too.

**Comment by Rookiestyle** [comment]
KeePassOTP 0.26 uses https://2fa.directory 

https://www.dongleauth.info/ doe snot provide the required json for download
