### ISSUE TITLE
Should 2FA supported site retrieval be more sophisticated?

### ISSUE THREAD

**Issue by leftdisconnected** [Rookiestyle/KeePassOTP#53]
Not a bug.  Feature is working as intended.

## Issue
This issue regards the feature which retrieves a JSON list of sites supporting OTP and links to their 2FA setup pages.

When KeePass is configured to autorun, users without full-time Internet connections get a pop-up error warning that KPOTP cannot access the 2FA site list.  This is expected, but should KeePassOTP behave in this way?

If a machine later obtains an Internet connection, the plugin does not seem to recheck after the initial startup error.  The KPOTP column continuously reports "Checking 2FA" during use and restarting KeePass appears to be the only method for retrying the JSON retrieval.

## Ideas
Does the plugin create a local file cache of this list?  If so, could the plugin be more sophisticated when throwing this error?  Perhaps it could show an error only if it failed to retrieve this file _and_ the local cache was more than 7 days old or whatever period seems appropriate.

Perhaps instead of the startup error, the plugin could show something like "Unknown 2FA" in non-configured KPOTP column fields and alter the control behavior such that double-clicking the fields would manually trigger a recheck for the JSON list.  If successful, the fields could be repopulated with "Setup 2FA" or emptied and the double-click behavior restored to normal.  If a failure occurs with a manual trigger, the error box should be shown regardless of cache age.

## Conclusion
This feature can be disabled in the plugin settings to avoid the error, but it seems unfortunate that it cannot cache the list and/or attempt to contact the server again some period of time after a failure.  I don't think that a cache would impose a security implication as it shouldn't expose which database entries have OTP configured.  The non-specific use of 2FA is already implied by the existence of the KeePassOTP PLGX.

Regardless, I thank you for the excellent plugin and for your valuable time in reading this.  Have a great day.

**Comment by Rookiestyle** [comment]
Thanks for your feedback.

I do not plan to cache the JSON list and am working on something like that instead
* Read JSON list of sites supporting OTP
* Show error message if first read attempt fails
* Retry every 30 seconds until list could be read
* Don't show error messages repeatedly during retry

**Comment by leftdisconnected** [comment]
Thank you.  I would think that 60-second or even longer retries would be good enough, but do what you think is the best and simplest behavior.

As you are working on an enhancement to this feature, feel free to close this issue if you like or I will close it if requested.  Thanks again for the time and energy that you've invested into KeePassOTP.
