### ISSUE TITLE
Feature to specify OTP field.

### ISSUE THREAD

**Issue by shellster** [Rookiestyle/KeePassOTP#60]
## Summary
Right now, to use this plugin, I need to go through all of my database and configure the OTP seeds for each account.  However, for recovery, I store my TOTP strings consistently in a field called OTP.  It would be great if there was a configuration option where you could specify such a field name, and then this plugin would automatically detect this field and use it for a seed unless a different seed had been explicitly configured for that entry.

To be clear, I routinely store my OTP seeds like this in a field called `OTP` (THIS IS NOT A REAL SEED):

`otpauth://totp/Example%3Abob%40example.com?secret=Z721ZADEZY7XAC81&issuer=Example`

If this feature were to be implemented, I would be able to go to the plugin configuration page, specify my default OTP filed as `OTP`, and from then on, the plugin would automatically be available on all seeds that were saved to the `OTP` field on existing and new entries.

**Comment by Rookiestyle** [comment]
What do you mean with "for recovery"?


You're right, KeePassOTP stores the otpauth string in a field called otp (lowercase).
I don't plan to make thies field name configurable.

If you create the OTP (uppercase) field using a plugin, I might be able to create a migration option - let me know the plugin's name in this case.
As an alternative option, you can use XML Replace (Tools -> Database Tools -> Tools...) to rename the field as shown in the screenshot

<span style="color:red">**Be careful when doing that and don't forget to make a backup before doing XML Replace**</span>

XML replace is described here: https://keepass.info/help/v2/xml_replace.html

Rename field from OTP to otp:
Find What: `(<Key>OTP</Key>)`
Replace With: `<Key>otp</Key>`
This should work if the field OTP contains a complete otpauth string

If field OTP only contains the seed:
Find What: `(<Key>MY_OTP_FIELD</Key>\s*<Value>(.*?)</Value>)`
Replace With: `<Key>otp</Key><Value>otpauth://totp?secret=$2</Value>`


![image](https://user-images.githubusercontent.com/36454520/122669304-fcc8b180-d1bc-11eb-84eb-2569849fae52.png)
