### ISSUE TITLE
KeePassOTP and connection ?

### ISSUE THREAD

**Issue by alexis26** [Rookiestyle/KeePassOTP#66]
[KeePass 2.48.1 and KeePassOTP 0.30]

Hi,
Does Kee[PassOTP work offline?
I recently had an internet problem and got the error message (see attached file) at startup...
as soon as I got my connection everything went back to normal...

is this normal?
and could not switch to the computer clock in the absence of connection?

Thank you
![pb connex keeP](https://user-images.githubusercontent.com/3404404/132991424-3dbe8f77-8b07-4ac6-bcd5-966f54c86460.png)

**Comment by Rookiestyle** [comment]
KeePassOTP works offline.

This KeePassOTP error message during KeePass start is normal in case of connection issues and it is **not** related to time settings.
Instead it is used to indicate whether you have accounts inyour database where two factor authentication is possible but not yet set up.

Have a look at KeePass' options or #62 / #57 for more information

**Comment by alexis26** [comment]
ah! ok...
I must have been on a group that has no otp configured and I only saw the error message in the KeePassOTP column without going to check on another group with otp configured ...
Sorry and thank you for answer
