### ISSUE TITLE
I hope KeeTrayTOTP on the tray can be color-coded, because similar accounts are difficult to choose

### ISSUE THREAD

**Issue by vipei** [Rookiestyle/KeePassOTP#75]
I hope KeeTrayTOTP on the tray can be color-coded, because similar accounts are difficult to choose

See this post

https://github.com/KeeTrayTOTP/KeeTrayTOTP/issues/176

**Comment by Rookiestyle** [comment]
It is not possible to change the text color because KeePass will change it to either black or white sometimes.
KeeTrayTOTP is also affected by that.

I am working on showing the entry icon and I can try to show the entry foreground color inside the icon,

**Comment by vipei** [comment]
> 无法更改文本颜色，因为 KeePass 有时会将其更改为黑色或白色。 KeeTrayTOTP 也受此影响。
> 
> 我正在显示条目图标，我可以尝试在图标内显示条目前景色，

Because of language barrier, the expression is not very clear. My thoughts should be consistent with yours.
 KeeTrayTOTP has realized my idea and hope that keepsotp will follow up.

**Comment by Rookiestyle** [comment]
> KeeTrayTOTP has realized my idea and hope that keepsotp will follow up.

Try this with KeePassTrayTotp and post a screenshot here please:
1. Change background color of entry to black
2. Change foreground color of entry to light blue
3. Open tray

When I do this, I can not read the text of the entry in the tray

**Comment by vipei** [comment]
[https://user-images.githubusercontent.com/49584327/139555121-d36b4635-4cfe-40d6-834c-03c98508845c.jpg](url)

Try

**Comment by Rookiestyle** [comment]
![image](https://user-images.githubusercontent.com/36454520/139585376-b0ba62be-d8ae-418c-aff0-1b00126dca8f.png)
That's what I meant.
KeePassTrayTotp changes the color and afterwards KeePass changes the textcolor back to black

Red line = You can't read the text
Orange line = Color coding does not work


I'm developing something that will work, this will take a few days.

**Comment by vipei** [comment]
> ![图片](https://user-images.githubusercontent.com/36454520/139585376-b0ba62be-d8ae-418c-aff0-1b00126dca8f.png) 我正是这个意思。 KeePassTrayTotp 更改颜色，然后 KeePass 将 textcolor 更改回黑色
> 
> 红线 = 您无法阅读文本 橙线 = 颜色编码不起作用
> 
> 我正在开发一些有用的东西，这需要几天时间。

That's true, but it's OK to avoid this color in normal use

**Comment by Rookiestyle** [comment]
> it's OK to avoid this color in normal use

For you it's ok.
For me it's not ok. If I do something like this, I want it to work for every color.

As I already wrote: I'm developing something that will work, this will take a few days.

**Comment by vipei** [comment]
> > 在正常使用中避免这种颜色是可以的
> 
> 对你来说没关系。 对我来说不行。如果我做这样的事情，我希望它适用于每种颜色。
> 
> 正如我已经写过的那样：我正在开发一些可以工作的东西，这需要几天时间。
If only I could speak English

**Comment by Rookiestyle** [comment]
Closed with 7aa5e25
