### ISSUE TITLE
Generate TOTP For Master Database Itself

### ISSUE THREAD

**Issue by t-p-tan** [Rookiestyle/KeePassOTP#8]
## Summary
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: Add the TOTP 2FA authenticator to the master database .kdbx file itself (i.e opening your own actual master database also requires TOTP). The secret for the key will be created as an entry "Master Database TOTP secret" and stored in the same manner as all other TOTP, either as entries or separately as a DB.

## Added value
[NOTE]: # (Describe how you and other users would benefit from this feature)

## Example
[NOTE]: # (Show a picture or a mock-up if applicable)

**Comment by Rookiestyle** [comment]
This is not possible.

You can't store a part of a database's masterkey inside this very database.
Somehow the TOTP you enter during database unlocking needs to be verified.
To do so, the stored secret needs to be read.
Reading the stored secret is not possible as long as the database is locked -> TOTP verification fails -> Database remains locked

In addition, TOTP does not offer any benefits in a local environment.
You might want to use the HOTP plugin available at [KeePass plugin page](https://keepass.info/plugins.html#otpkeyprov)

**Comment by t-p-tan** [comment]
Oops yeah. You are right.
