### ISSUE TITLE
Crash at startup without working network

### ISSUE THREAD

**Issue by Nama** [Rookiestyle/KeePassOTP#81]
## Overview
[TIP]: # (DO NOT include screenshots of your actual database)
[TIP]: # (DO NOT post sensitive data of any kind)
[NOTE]: # (Give a BRIEF summary about your problem)
A connection error to the list with supported 2FA causes KeePass to crash.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug)
1. Don't have internet
2. Start KeePass

## Expected Behavior
[NOTE]: # (Describe how you expect the plugin to behave)
Work without internet x)

## Actual Behavior
[NOTE]: # (Describe how the plugin actually behaves)
Shows an error, that the website wasn't reachable and KeePass crashed after I clicked OK.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Windows 10
KeePass Version: 2.49
Plugin Version: 1.1.1

[NOTE]: # (If possible, please attach a debug file. Have a look at the wiki for details.)

**Comment by Rookiestyle** [comment]
This will be fixed soon.
