### ISSUE TITLE
What are the conditions for autofill via hotkey to work?

### ISSUE THREAD

**Issue by robertl87** [Rookiestyle/KeePassOTP#83]
(Thanks for this really helpful plugin!)

While writing a help request, I found out that you need to have the entry title the same¹ as the webpage title for autofill via global hotkey to work. Maybe it's good to add this to the readme. How are the conditions exactly? Should the title contain a part, or be an exact match?

I had a struggle with a page titled "server.example.com - DirectAdmin v1.2.3"
If I set the entry in KeePass to "DirectAdmin" OTP autotype works.
¹If I set it to one of the following, it doesn't work:
* server.example.com - DirectAdmin v1.2.3
* server.example.com
* DirectAdmin (identification)
* server.example.com DirectAdmin

P.S. On the wiki there's a link to a 404 page: https://github.com/Rookiestyle/KeePassOTP/KeePassOTP-storage-approaches#otp-storage-within-the-respective-entry
I was looking for a way to export existing OTP data to OTP storage in a separate database, because it seems you need to start over when selecting that option, right?

**Comment by Rookiestyle** [comment]
> How are the conditions exactly?

See *How it works - Details* here: https://keepass.info/help/base/autotype.html#autoglobal
If this does not work for KeePassOTP' hotkey but KeePass' Global Auto-T>ype hotkey works, please post more details here.

> I was looking for a way to export existing OTP data to OTP storage in a separate database, because it seems you need to start over when selecting that option, right?

If my understandig is correct, you already have OTP data set up and now want to move those into the embedded database of KeePassOTP?
Use the options as mentioned in the readme <img src="https://github.com/Rookiestyle/KeePassOTP/raw/master/images/KeePassOTP%20-%20options.png"></img>
You can create the mebedded db and also move OTP data from the main db into the embedded db (Entry -> DB)

I fixed the wrong link, thanks for letting me know.

**Comment by robertl87** [comment]
Hmm, must have missed that page. Thanks!
