### ISSUE TITLE
Translation: <language>

### ISSUE THREAD

**Issue by xex89** [Rookiestyle/KeePassOTP#84]
[NOTE]: # (Please do not forget to attach the translation file)
Language: 
- [x] New translation
- [ ] Update existing translation
- [ ] If updated: Only added missing Texts
- [ ] All relevant texts translated

[NOTE]: # (A text is relevant if the standard text in english language is NOT sufficient)

**Comment by xex89** [comment]
Arabia

**Comment by Rookiestyle** [comment]
Please attach the language file, I can't do the translation
