### ISSUE TITLE
Update Issuer or username from database

### ISSUE THREAD

**Issue by pitdicker** [Rookiestyle/KeePassOTP#95]
## Summary
Update issuer and username in the `otpauth://` string when editing the OTP data of an existing entry.

## Added value
On some of the sites where I use 2FA I changed my email-address. Also I changed the issuer name in a few cases, for example from 'Firefox Sync' to 'Firefox'.
These changes are easy to make in the KeePass database, but the `otpauth://` string doesn't automatically update.
Now it doesn't have to happen automatically (the less silent changes there are to my password database the better), but it would be nice if the string is updated after opening the setup dialog and pressing OK.

I could try to make the change myself, but haven't found the right place yet, and would like to know if you agree this makes sense.

**Comment by Rookiestyle** [comment]
I'm currently working on an export option to Google Authenticator and will work on this one afterwards.

**Comment by pitdicker** [comment]
Thank you!
