### ISSUE TITLE
Allow "Copy OTP" even when database is locked

### ISSUE THREAD

**Issue by gabriele-v** [Rookiestyle/KeePassOTP#97]
## Summary
I'm using KeePassOTP with separate database and without auto-open at startup (I'm opening it only when I need a 2FA).

It would be helpful to have the menu "Copy OTP" enabled even when KeePassOTP database is locked, otherwise when I have the main DB already opened, I have to click "OTP Setup" which is the only one enabled, then enter the password, close the setup windows and right click again copying the OTP.

## Added value
Less clicks needed, it will ask for the password and then copy the OTP.

**Comment by Rookiestyle** [comment]
Working on it.

In the meantime you might want to enable the KPOTP column.
You can doubleclick it to copy the OTP. If the OTP is locked, you'll be asked to unlock.
In KeePassOTP's options you can decide whether to display the OTP value or only the OTP status (OTP defined / OTP can be defined)

**Comment by gabriele-v** [comment]
Cool, I've never tried to double click that column 😅
